export interface Course {
  id: string | number;
  title: string;
  description: string;
  instructor: string;
  category: string;
  difficulty: string;
  price: string | number;
  originalPrice?: number;
  rating: number;
  students: number;
  duration: string;
  lessons?: number;
  createdAt?: string;
  updatedAt?: string;
  thumbnail?: string;
  isNew?: boolean;
  isPopular?: boolean;
  isBestseller?: boolean;
  tags?: string[];
  features?: string[];
}

export const mockCourses: Course[] = [
  {
    id: "1",
    title: "Complete Python Programming Bootcamp",
    description: "Learn Python from scratch with hands-on projects and real-world applications. Perfect for beginners who want to become proficient in Python programming.",
    instructor: "Dr. Sarah Johnson",
    category: "ai",
    difficulty: "Beginner",
    price: "250 coins",
    originalPrice: 350,
    rating: 4.8,
    students: 12450,
    duration: "42 hours",
    lessons: 156,
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-01-20T00:00:00Z",
    thumbnail: "/api/placeholder/400/225",
    isNew: true,
    isPopular: true,
    tags: ["python", "programming", "beginner", "projects"],
    features: ["Lifetime access", "Certificate of completion", "42 hours of video", "Downloadable resources"],
  },
  {
    id: "2",
    title: "Advanced Machine Learning with TensorFlow",
    description: "Master machine learning concepts and build sophisticated AI models using TensorFlow and Keras. Includes neural networks, deep learning, and computer vision.",
    instructor: "Prof. Michael Chen",
    category: "ai",
    difficulty: "Advanced",
    price: "450 coins",
    originalPrice: 600,
    rating: 4.9,
    students: 8920,
    duration: "65 hours",
    lessons: 89,
    createdAt: "2024-01-10T00:00:00Z",
    updatedAt: "2024-01-18T00:00:00Z",
    thumbnail: "/api/placeholder/400/225",
    isBestseller: true,
    tags: ["machine learning", "tensorflow", "ai", "deep learning"],
    features: ["Advanced projects", "Industry case studies", "Code templates", "1-on-1 mentorship"],
  },
  {
    id: "3",
    title: "Calculus I: Limits and Derivatives",
    description: "Comprehensive introduction to calculus covering limits, continuity, derivatives, and their applications. Perfect for students preparing for advanced mathematics.",
    instructor: "Dr. Emily Rodriguez",
    category: "math",
    difficulty: "Intermediate",
    price: "180 coins",
    rating: 4.7,
    students: 15670,
    duration: "38 hours",
    lessons: 124,
    createdAt: "2024-01-05T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
    thumbnail: "/api/placeholder/400/225",
    tags: ["calculus", "mathematics", "derivatives", "limits"],
    features: ["Interactive exercises", "Step-by-step solutions", "Practice problems", "Formula sheets"],
  },
  {
    id: "4",
    title: "Digital Marketing Mastery",
    description: "Complete guide to digital marketing including SEO, social media marketing, email campaigns, and analytics. Build a successful online presence.",
    instructor: "Mark Thompson",
    category: "business",
    difficulty: "Beginner",
    price: "Free",
    rating: 4.5,
    students: 25340,
    duration: "28 hours",
    lessons: 95,
    createdAt: "2024-01-12T00:00:00Z",
    updatedAt: "2024-01-22T00:00:00Z",
    thumbnail: "/api/placeholder/400/225",
    isPopular: true,
    tags: ["marketing", "seo", "social media", "business"],
    features: ["Free course", "Real campaigns", "Tools and templates", "Community access"],
  },
  {
    id: "5",
    title: "Organic Chemistry Fundamentals",
    description: "Master the basics of organic chemistry including molecular structure, reactions, and mechanisms. Essential for pre-med and chemistry students.",
    instructor: "Dr. Lisa Park",
    category: "science",
    difficulty: "Intermediate",
    price: "320 coins",
    originalPrice: 420,
    rating: 4.6,
    students: 7890,
    duration: "52 hours",
    lessons: 178,
    createdAt: "2024-01-08T00:00:00Z",
    updatedAt: "2024-01-20T00:00:00Z",
    thumbnail: "/api/placeholder/400/225",
    tags: ["chemistry", "organic", "reactions", "mechanisms"],
    features: ["3D molecular models", "Reaction animations", "Practice exams", "Lab simulations"],
  },
  {
    id: "6",
    title: "UI/UX Design Complete Course",
    description: "Learn user interface and user experience design from concept to completion. Master Figma, design systems, and user research methodologies.",
    instructor: "Alex Rivera",
    category: "art",
    difficulty: "Beginner",
    price: "280 coins",
    rating: 4.8,
    students: 18920,
    duration: "45 hours",
    lessons: 132,
    createdAt: "2024-01-14T00:00:00Z",
    updatedAt: "2024-01-25T00:00:00Z",
    thumbnail: "/api/placeholder/400/225",
    isNew: true,
    tags: ["ui", "ux", "design", "figma"],
    features: ["Design portfolio", "Figma masterclass", "User research", "Industry projects"],
  },
  {
    id: "7",
    title: "Spanish Conversation Mastery",
    description: "Learn to speak Spanish fluently through interactive conversations and real-world scenarios. Perfect for beginners and intermediate learners.",
    instructor: "Maria Gonzalez",
    category: "language",
    difficulty: "Beginner",
    price: "150 coins",
    rating: 4.7,
    students: 4100,
    duration: "4 weeks",
    lessons: 28,
    createdAt: "2024-01-20T00:00:00Z",
    updatedAt: "2024-01-25T00:00:00Z",
    thumbnail: "/api/placeholder/400/225",
    tags: ["spanish", "language", "conversation", "beginner"],
    features: ["Interactive dialogues", "Pronunciation guide", "Cultural insights", "Practice exercises"],
  },
  {
    id: "8",
    title: "Music Theory and Composition",
    description: "Master the fundamentals of music theory and learn to compose your own pieces. From basic scales to advanced harmony.",
    instructor: "Elena Vasquez",
    category: "music",
    difficulty: "Beginner",
    price: "200 coins",
    rating: 4.5,
    students: 2100,
    duration: "3 weeks",
    lessons: 21,
    createdAt: "2024-01-18T00:00:00Z",
    updatedAt: "2024-01-23T00:00:00Z",
    thumbnail: "/api/placeholder/400/225",
    tags: ["music", "theory", "composition", "beginner"],
    features: ["Interactive lessons", "Composition tools", "Audio examples", "Practice exercises"],
  },
];
