import { Card } from "../flashcards/types";

export const mockDecks = [
  {
    id: 1,
    name: "Physics Fundamentals",
    count: 45,
    difficulty: "medium",
    topic: "Physics",
  },
  {
    id: 2,
    name: "Organic Chemistry",
    count: 32,
    difficulty: "hard",
    topic: "Chemistry",
  },
  {
    id: 3,
    name: "Spanish Vocabulary",
    count: 150,
    difficulty: "easy",
    topic: "Language",
  },
];

export const mockCards: Card[] = [
  {
    id: 1,
    front: "What is Newton's First Law of Motion?",
    back: "An object at rest stays at rest and an object in motion stays in motion with the same speed and in the same direction unless acted upon by an unbalanced force. This is also known as the Law of Inertia.",
    hasAudio: true,
    difficulty: "medium",
    timesReviewed: 12,
    timesCorrect: 9,
    lastReviewed: new Date("2024-01-15"),
    nextReview: new Date("2024-01-18"),
    mastery: "review",
    tags: ["physics", "mechanics", "fundamental-laws"],
  },
  {
    id: 2,
    front: "What is the formula for kinetic energy?",
    back: "KE = ½mv²\n\nWhere:\n• m = mass (kg)\n• v = velocity (m/s)\n• KE = kinetic energy (Joules)",
    hasAudio: false,
    difficulty: "easy",
    timesReviewed: 8,
    timesCorrect: 7,
    lastReviewed: new Date("2024-01-14"),
    nextReview: new Date("2024-01-16"),
    mastery: "mastered",
    tags: ["physics", "energy", "formulas"],
  },
  {
    id: 3,
    front: "What is the SI unit of force?",
    back: "Newton (N)\n\n1 Newton = 1 kg⋅m/s²\n\nNamed after Sir Isaac Newton, it represents the force needed to accelerate 1 kilogram of mass at 1 meter per second squared.",
    hasAudio: true,
    difficulty: "easy",
    timesReviewed: 15,
    timesCorrect: 14,
    lastReviewed: new Date("2024-01-16"),
    nextReview: new Date("2024-01-20"),
    mastery: "mastered",
    tags: ["physics", "units", "force"],
  },
  {
    id: 4,
    front: "Define acceleration and provide its formula",
    back: "Acceleration is the rate of change of velocity with respect to time.\n\na = Δv/Δt = (v₂ - v₁)/(t₂ - t₁)\n\nWhere:\n• a = acceleration (m/s²)\n• Δv = change in velocity\n• Δt = change in time",
    hasAudio: false,
    difficulty: "hard",
    timesReviewed: 5,
    timesCorrect: 2,
    lastReviewed: new Date("2024-01-13"),
    nextReview: new Date("2024-01-15"),
    mastery: "learning",
    tags: ["physics", "kinematics", "formulas"],
  },
  {
    id: 5,
    front: "What is gravitational potential energy?",
    back: "Gravitational potential energy is the energy possessed by an object due to its position in a gravitational field.\n\nPE = mgh\n\nWhere:\n• PE = potential energy (J)\n• m = mass (kg)\n• g = gravitational acceleration (9.8 m/s²)\n• h = height above reference point (m)",
    hasAudio: true,
    difficulty: "medium",
    timesReviewed: 3,
    timesCorrect: 3,
    lastReviewed: new Date("2024-01-12"),
    nextReview: new Date("2024-01-14"),
    mastery: "new",
    tags: ["physics", "energy", "gravity"],
  },
];