name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - run: go mod download
      - run: make proto
      - run: go vet ./...
      - run: go test ./...
      - run: docker build -t ghcr.io/example/edu-backend:latest .
